"""link orders to users

Revision ID: 163c5bcb3e5d
Revises: c1b6f639b1e6
Create Date: 2026-08-24 00:51:10.911052

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "163c5bcb3e5d"
down_revision: str | Sequence[str] | None = "c1b6f639b1e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_foreign_key(
        None, "orders", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_column("orders", "user_id")
    # ### end Alembic commands ###
