"""add order idempotency

Revision ID: 6bf04a07e609
Revises: 163c5bcb3e5d
Create Date: 2026-08-24 01:16:22.989241

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bf04a07e609"
down_revision: str | Sequence[str] | None = "163c5bcb3e5d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("idempotency_key", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("request_fingerprint", sa.String(length=64), nullable=True)
    )
    op.create_unique_constraint(
        "uq_orders_user_id_idempotency_key", "orders", ["user_id", "idempotency_key"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_orders_user_id_idempotency_key", "orders", type_="unique")
    op.drop_column("orders", "request_fingerprint")
    op.drop_column("orders", "idempotency_key")
    # ### end Alembic commands ###
