"""add product category and image path

Revision ID: c79eb3c9c11b
Revises: 1415b1ed446e
Create Date: 2026-08-21 00:16:58.589042

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c79eb3c9c11b"
down_revision: str | Sequence[str] | None = "1415b1ed446e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "category", sa.String(length=80), server_default="Other", nullable=False
        ),
    )
    op.add_column(
        "products", sa.Column("image_path", sa.String(length=500), nullable=True)
    )
    op.create_index(
        op.f("ix_products_category"), "products", ["category"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_category"), table_name="products")
    op.drop_column("products", "image_path")
    op.drop_column("products", "category")
    # ### end Alembic commands ###
